### PR TITLE
Bump play versions to 2.5.4

### PR DESCRIPTION
**Pull request by mikem**
I included HALselhof 0.1.0 in my Play 2.5.4 project. When serializing a `HalResource` instance to JSON, this exception occurs:

```
java.lang.RuntimeException: java.lang.NoSuchMethodError: play.api.libs.json.JsObject.<init>(Lscala/collection/Seq;)V
```

I believe this is because HALselhof 0.1.0 was compiled against play-json 2.4.0 which has a binary incompatibility with play-json 2.5.4. Applying the changes in this PR, rebuilding and publishing to my local Ivy cache resolved the issue for me.

I'd love to learn how multiple versions of this library compiled against the various play-json versions can be provided. Also, I'm not sure how the HALSelhof version should be adjusted. See also #1.

### CODE REVIEW

**Comment by dwestheide** [comment]
Thanks a lot, @mikem - now that I am back from vacation, I was able to review your PR. Looks good to me. 👍 

I am going to merge this as is, and I will open an issue about providing artifacts for multiple different play-json versions at the same time.

**Comment by dwestheide** [comment]
Released in version 0.2.0: https://bintray.com/restfulscala/maven/halselhof/0.2.0

**Comment by mikem** [comment]
Awesome, thanks @dwestheide. I can confirm my project now works with 0.2.0.
